### ISSUE TITLE
Error when trying to turn around your character

### ISSUE THREAD

**Issue by ZiggyJoJo** [pedr0fontoura/fivem-appearance#15]
No ones posted it yet but I've noticed a few other people mention having this issue since the last release if you try to use the button to turn around your character they don't move and you get this error 
https://i.imgur.com/cJA5h4n.png

**Comment by dunak-debug** [comment]
can reproduce

**Comment by dunak-debug** [comment]
fixed in https://github.com/pedr0fontoura/fivem-appearance/commit/af0d1874526e21f8f4e16802d41d86a8d12ddbc9
