### ISSUE TITLE
Some problems trying to build it.

### ISSUE THREAD

**Issue by deenz-dev** [pedr0fontoura/fivem-appearance#18]
Thats my problem im for sure, i was wondering if you can release it already buildt, i would aprecciate it so much, thanks <3

**Comment by auraroleplay** [comment]
same here. Prettier errors are spamming. Cant build

**Comment by pedr0fontoura** [comment]
Can you check after 214f950 ?

**Comment by auraroleplay** [comment]
Build working for me. But second button for camera is still not reseting camera angle. There is no error this time.

**Comment by pedr0fontoura** [comment]
Since the building problem is fixed, i'll close this issue.



> Build working for me. But second button for camera is still not reseting camera angle. There is no error this time.

@auraroleplay please open another issue with more details if possible.
