### ISSUE TITLE
tattoos

### ISSUE THREAD

**Issue by CyanFlare** [pedr0fontoura/fivem-appearance#22]
Hello, I was wondering when tattoos will be added to fivem-appearence. I've seen it on the to-do list on the cfx.re post for a while now and was curious on when it will be implemented. Would be nice to have all character customizations in one place instead of a different menu just for tattoos.

Thanks.

**Comment by ansljeremy** [comment]
This is the one thing that is stopping me from swapping my server to this

**Comment by DistrictZion** [comment]
Still waiting...

**Comment by franfdezmorales** [comment]
Im currently working on this, on few days will be released 👍

**Comment by franfdezmorales** [comment]
Finally i have enough time to almost finish this feature, btw its not finished 100%, in few days i will pr the full feature. Currently waiting to get an approval of #34.
[Video of current work](https://streamable.com/z8ceh5).

**Comment by ansljeremy** [comment]
@franfdezmorales Honestly I would just PR https://github.com/ihyajb/aj-fivem-appearance since it's more alive

**Comment by franfdezmorales** [comment]
@ansljeremy I think the pr need to be done here since its the standalone and principal recourse, others are forks.

**Comment by franfdezmorales** [comment]
Currently finished this feature, here a video of how tattoos work with fivem-appearance: https://streamable.com/04zqto

**Comment by franfdezmorales** [comment]
Feature added! #35 🥳
