### ISSUE TITLE
add hair variation two

### ISSUE THREAD

**Issue by lush0n3** [pedr0fontoura/fivem-appearance#39]
### **On my server I use modified hairstyles and sometimes the original hair overlaps.**

**example:**
![image](https://user-images.githubusercontent.com/87586904/166421839-b31b62e1-f075-418c-b485-129a33a27cfa.png)

**and it should actually look like this.**
![image](https://user-images.githubusercontent.com/87586904/166422058-561989fe-57b8-495e-a390-b438d5014246.png)

**I can give you more information if you need it, the main problem is that component number two seems to activate the original hairstyle.**

Thank you for your time and for your excellent work!

**Comment by franfdezmorales** [comment]
Currently working on this!

**Comment by franfdezmorales** [comment]
Currently finished, here a preview:

https://user-images.githubusercontent.com/47320936/167225661-be961c76-3ca8-4110-837c-1a176dfe1bbe.mp4

**Comment by lush0n3** [comment]
> Currently finished, here a preview:
> 
>  uklbk3s.mp4

Perfect, when will you compile a new version to use it?

**Comment by franfdezmorales** [comment]
@lush0n3 I dont know, i need to get approved another pr, then it should be available.

**Comment by lush0n3** [comment]
Perfect, thank you very much, thank you for your time and work.
