### ISSUE TITLE
Makeup secondary colors

### ISSUE THREAD

**Issue by Senlar** [pedr0fontoura/fivem-appearance#40]
Females have noticed the secondary makeup colors are not customizable in this menu. They say it appears the secondary color is defaulting to some shade of pink. Please consider adding secondary color to makeup options.

**Comment by franfdezmorales** [comment]
Hey @Senlar, could you attach some pics or videos replicating the error? Ty in advance!

**Comment by Senlar** [comment]
Of course, here is what I was provided @franfdezmorales 
https://medal.tv/games/gta-v/clips/k9vHb53VTxSgw/d1337u7NmDAE?invite=cr-MSxvamIsMjIxNjIwNzks

Pretty much the make up section doesn't have an option to change the secondary color, and for whatever reason it is defaulting to pink. I even friend changing my blush and lipstick color to see if maybe those would fix anything.

**Comment by franfdezmorales** [comment]
Fixed on #54, ty @YisusOnDev!
