### ISSUE TITLE
input sanitization

### ISSUE THREAD

**Issue by chunce01** [pedr0fontoura/fivem-appearance#45]
Need to limit the amount of 0's that can be input on range values to prevent resource crashing.

**Comment by franfdezmorales** [comment]
Hey, could you provide some media about the error?

**Comment by chunce01** [comment]
Actually, feel free to close this ticket out, I cannot seem to reproduce it. However, what I did previously was if you filled the range field with too many 0's it would break the clothing menu UI.
![image](https://user-images.githubusercontent.com/26256782/169858909-653cd3db-207d-43e3-aa88-7aa8d5f6e2e5.png)

**Comment by franfdezmorales** [comment]
Hey, i will take a look into this in the next few days, tried many times but still cannot reproduce the error. :(
