### ISSUE TITLE
When You Leave And Join It Resets Your skin

### ISSUE THREAD

**Issue by Wopskinoo** [pedr0fontoura/fivem-appearance#46]
so the menu itself is working fine but for some reason when you fly in and out it resets you back to a ped and you have to remake your player help asap

**Comment by franfdezmorales** [comment]
Hey, this resource only provides the way to customize your character but you will need to work with the exports to make the ped skin persistent.

**Comment by Wopskinoo** [comment]
> 

Do you have one that’s setup already? I want to use that menu as my main menu but idk how to fix it or could you explain it

**Comment by franfdezmorales** [comment]
Hello, you will need to use the getters exports to receive all the data clothes, then you will need to save on database. When a player join into your server, you will need to get the data from database, then use the setters exports to change the outfit of your character.

**Comment by Wopskinoo** [comment]
Walk through maybe?

**Comment by franfdezmorales** [comment]
There are a lot of variables to do a correct walk through, btw, you can ask whatever you need to know to get your objectives.
