### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by s0u007** [pedr0fontoura/fivem-appearance#55]
Hi how can i use setPedComponent ? I have this code:

	local playerPed = PlayerPedId()
	local cos1 = '[{"drawable":6,"component_id":4,"texture":0}]'
	local cos = exports['fivem-appearance']:setPedComponent(playerPed, cos1)

	exports['fivem-appearance']:setPedComponent(playerPed, cos1 )
	print(cos)

and I am getting print saying nil

also how can I update my version with lua files ?

**Comment by franfdezmorales** [comment]
Hey! You need to pass and object, not an array with a object. The set function is a void so doesnt return anything. If you need to make this code works, try this: 
```lua 
exports['fivem-appearance']:setPedComponent(PlayerPedId(), {drawable = 6, component_id = 4, texture = 0})
```
I dont understand the question "also how can I update my version with lua files ?", could you explain a bit more? 
Really ty!

**Comment by s0u007** [comment]
That's a lot it is working. Explaing I have and older verios without tattos and stuff. I downlowded it from some with ready lua files and now I want to update this script without making lua part again. I want to get the tattoo option the most

**Comment by franfdezmorales** [comment]
If you have downloaded from another site, its hard to make it work with current version of this script. 
I recommend that you download the current version [(1.3.1)](https://github.com/pedr0fontoura/fivem-appearance/releases/tag/v1.3.1).

**Comment by s0u007** [comment]
So waht should I do now, because I don't start again with lua files

**Comment by franfdezmorales** [comment]
If you want to **use** this script, you just need to use the exports, dont worry about languages,  it will work on `lua`, `ts`, `js`, `c#` files. If you have other version, you could replace with [this](https://github.com/pedr0fontoura/fivem-appearance/releases/tag/v1.3.1). 
If you want to **modify** this script, then you will need to download the source, and make your modifications.
