### ISSUE TITLE
setComponets problem

### ISSUE THREAD

**Issue by s0u007** [pedr0fontoura/fivem-appearance#58]
Hi it is me one more time can you help me with this issue ?
exports['fivem-appearance']:setPedAppearance(PlayerPedId(), {texture=0,drawable=0,component_id=0},{texture=0,drawable=0,component_id=1},{texture=0,drawable=0,component_id=2},{texture=0,drawable=15,component_id=3},{texture=0,drawable=14,component_id=4},{texture=0,drawable=0,component_id=5},{texture=0,drawable=5,component_id=6},{texture=0,drawable=0,component_id=7},{texture=0,drawable=15,component_id=8},{texture=0,drawable=0,component_id=9},{texture=0,drawable=0,component_id=10},{texture=0,drawable=91,component_id=11})

I want to use this export but noting is changing with character what can I do ?

**Comment by franfdezmorales** [comment]
Hey @s0u007, the function expects only two parameters, the ped id and the PedAppearance object that must include all these keys: 
 - model: string;
 - components: PedComponent[];
 - props: PedProp[];
 - headBlend: PedHeadBlend;
 - faceFeatures: PedFaceFeatures;
 - headOverlays: PedHeadOverlays;
 - hair: PedHair;
 - eyeColor: number;
 - tattoos: TattooList;

You need to change your seconds parameter and fill with that above.
