### ISSUE TITLE
appearance cutoff

### ISSUE THREAD

**Issue by DarinBeard** [pedr0fontoura/fivem-appearance#59]
When I expand the appearance section it can scroll down to the very top of Moles and Freckles and the rest is cut off. Anyone else have that problem?

**Comment by DarinBeard** [comment]
![image](https://user-images.githubusercontent.com/793744/174677552-0f28a756-e466-4206-b7b7-119a64cdb8bb.png)

**Comment by franfdezmorales** [comment]
Hey @DarinBeard, try to use tab when that happens, will probably fix it.

**Comment by DarinBeard** [comment]
Ya, if I click on the Mole and Freckles header and hit TAB it expands. A little janky but works. Thanks.
