### ISSUE TITLE
turn around error

### ISSUE THREAD

**Issue by DarinBeard** [pedr0fontoura/fivem-appearance#60]
getting an error when the turn around button is clicked

SCRIPT ERROR in event `__cfx_nui:appearance_turn_around': TypeError: OpenSequenceTask is not a function or its return value is not iterable
@fivem-appearance/typescript/build/client.js:1
@fivem-appearance/typescript/build/client.js:1

**Comment by franfdezmorales** [comment]
Hey @DarinBeard, could you pls provide more info about the error? 

- When happens? 
- It happens every time or sometimes? 
- What happens on game when the error is triggered?

**Comment by DarinBeard** [comment]
it happens when the turn around button is clicked.

it's happens every time.

I click the button, the error message hits the console and the button just untoggles itself with nothing happening at all. If I click the rotate buttons the camera then spins around behind the character like it thinks it did the spin already. Clicking it again and clicking the rotate takes it back to the front like it is toggled off. See video attached for demo.

I also will add that I am using your build and have changed nothing in the fivem-appearance tools.

https://user-images.githubusercontent.com/793744/174833991-632b710e-1fc2-42c7-8bdc-72b9ac2ecfae.mp4

**Comment by DarinBeard** [comment]
the build that [SpalenyBramborak](https://github.com/SpalenyBramborak) gave me fixed the issue
