### ISSUE TITLE
ui error on load causes menu to not show 

### ISSUE THREAD

**Issue by DarinBeard** [pedr0fontoura/fivem-appearance#61]
Sometimes, (maybe 1 out of 5 times) when the resource is started, it throws an error and the menu will not show. The resource has to be restarted before it will show. see video for demo.

error: Uncaught (in promise) SyntaxError: Unexpected end of JSON input (@fivem-appearance/ui/build/index.html:1)

**Comment by DarinBeard** [comment]
video didn't upload correctly.

https://user-images.githubusercontent.com/793744/174836049-f0ed7f02-2a90-44cb-bbfa-f88015b06598.mp4

**Comment by DarinBeard** [comment]
Man, I have no idea how to yarn build this thing. I've never done it and I tried and I can't tell what to do with the output because it doesn't look anything like the build I downloaded.

**Comment by SpalenyBramborak** [comment]
[fivem-appearance.zip](https://github.com/pedr0fontoura/fivem-appearance/files/8952161/fivem-appearance.zip)

**Comment by DarinBeard** [comment]
You are the man, thank you very much.
