### ISSUE TITLE
tattoos

### ISSUE THREAD

**Issue by DarinBeard** [pedr0fontoura/fivem-appearance#63]
Am I just missing them or at tattoos not in there as of yet?

**Comment by franfdezmorales** [comment]
Hello @DarinBeard, maybe you're using a wrong config, try this: 

```lua
    ped = true,
    headBlend = true,
    faceFeatures = true,
    headOverlays = true,
    components = true,
    props = true,
    tattoos = true
```

**Comment by DarinBeard** [comment]
nope, totally my fault. It wasn't in my config. Thank you, guys, for being responsive. That's super cool. 

This is an excellent resource that I've implemented on our server and got it saving to the database with a menu that allows management of multiple characters per player. So thank you for the great resource.

![fivem exe 2022 06 22 - 14 59 13 05 mp4_20220623_095127 633](https://user-images.githubusercontent.com/793744/175315887-08a9f0eb-f3b3-4cd3-8574-60fe9fe4388e.jpg)
.
