### ISSUE TITLE
unable to add new tattoos

### ISSUE THREAD

**Issue by ChurchTG7** [pedr0fontoura/fivem-appearance#64]
when i try to add new tattoos using the same 

    {
        "name": "hair-32-4",
        "label": "hair-32-4",
        "hashMale": "MP_Security_Hair_000_M",
        "hashFemale": "MP_Security_Hair_000_F",
        "zone": "ZONE_HAIR",
        "collection": "mpSecurity_overlays"
    }

but change it for one of the tats i have from GTA5-mods.com

    {
        "name": "Yakuza Tat 1",
        "label": "Yakuza Tat 1",
        "hashMale": "sp_fr_tat_000",
        "hashFemale": "sp_fr_tat_000",
        "zone": "ZONE_TORSO",
        "collection": "mpSecurity_overlays"
    }

it doesn't work where did i go wrong?

**Comment by franfdezmorales** [comment]
Hey @ChurchTG7, `json` looks fine, maybe the problem is on how you stream the new tattoos.

**Comment by ChurchTG7** [comment]
yea i figured as much just need to figure out why they aren't streaming correctly thanks anyways

**Comment by franfdezmorales** [comment]
Thats perfect! I close this issue.
