### ISSUE TITLE
Resource optimization

### ISSUE THREAD

**Issue by irineudores** [pedr0fontoura/fivem-appearance#69]
When opening the interface once, even after closing, it continues using cpu, as if it were in a loop. Is it possible to optimize this? Or at least I wanted to understand why stay in a loop when the system is not even being used

**Comment by franfdezmorales** [comment]
Hey @irineudores, no loops are active when you dont use the resource. JS performance is worse (not a lot) than lua on FiveM, the resource itself consume 0.01 ms, talking about computing time, thats ridiculous.
