### ISSUE TITLE
@fivem-appearance/server.lua:15: attempt to index a nil value (local 'xPlayer')

### ISSUE THREAD

**Issue by esFer102** [pedr0fontoura/fivem-appearance#72]
This error shows me when I try to create a new character:
`@fivem-appearance/server.lua:15: attempt to index a nil value (local 'xPlayer')`

**Comment by franfdezmorales** [comment]
Hey @esFer102!
Looks like an error with ESX, this resource is standalone so its not an issue about the script.

**Comment by esFer102** [comment]
Okey, I'll take a look. Thanks
