### ISSUE TITLE
startPlayerCustomization Export

### ISSUE THREAD

**Issue by avery1227** [pedr0fontoura/fivem-appearance#8]
Hello, 

First off I want to say this is an amazing released and to keep up the good work.

Secondly, I do have an issue currently.

When a player connects to the server and Triggers the startPlayerCustomization (Trigged From a Menu after they are loaded in) It sometimes will throw them into NUI Focus (cursor) but no UI will render.

I am running the newest version of the resource (several hours ago).

It seems the only way to get it to work is to restart the fivem-appearance resource once the player has already joined the server.

**Comment by avery1227** [comment]
Details I forgot:

It does set the camera to be in-front just the UI will not render in unless I restart the script after the player is already loaded in.

**Comment by avery1227** [comment]
**Video:** https://files.cadojrp.com/194tlmXTEvdR.mp4

**Comment by avery1227** [comment]
Now that I'm home I was able to pinpoint this:

```
[     83625] [b2189_GTAProce]             MainThrd/ Creating script environments for fivem-appearance
[     83828] [b2189_GTAProce]             MainThrd/ Still executing script initialization routines...
[     83906] [b2189_GTAProce]             CrBrowserMain/ Uncaught (in promise) SyntaxError: Unexpected end of JSON input (@fivem-appearance/ui/build/index.html:1)
```

Line 3 is what piqued my interest. It only seems to happen on player connecting not resource starting when already connected.

**Comment by avery1227** [comment]
Could it possibly be related to?

https://github.com/snakewiz/fivem-appearance/blob/a13625b9181cf0cb228d5a7af70cd666b2194efd/typescript/src/client/index.ts#L19

**Comment by TzProwebyKS** [comment]
I have the same problem but if I add Wait(5000) or Citizen.Wait(5000) before calling startPlayerCustomization it works fine!

**Comment by RockySouthpaw** [comment]
I personally dont have the export error but i also have the UI not rendering same as you.

It's most likely related to the json erro though as I have that too:
![FiveM_b2060_GTAProcess_1Ffsykfb4p](https://user-images.githubusercontent.com/55056068/117524706-82392f00-af8c-11eb-8bdc-9c0d057eea7b.png)

**Comment by RockySouthpaw** [comment]
> On my sv happens the same as @avery1227, u need to ensure the script when player load, otherwise dont work.

I assume you have the convars set in your server.cfg

**Comment by avery1227** [comment]
The convars were set before ensuring the script in the CFG

**Comment by RockySouthpaw** [comment]
@avery1227 Just to confirm, you downloaded from the release tab correct? Or did you manually build it?

**Comment by Cyntaax** [comment]
I actually experienced this myself, I fixed it by moving the entire `init()` function to just global context rather than running it on script start. 

I remembered there was something weird about exports and them having to be run on the first tick and made me give it a try. works like a charm now.

**Comment by ElSeba0811** [comment]
> I actually experienced this myself, I fixed it by moving the entire `init()` function to just global context rather than running it on script start.
> 
> I remembered there was something weird about exports and them having to be run on the first tick and made me give it a try. works like a charm now.

can you show how and where you did it?

**Comment by Cyntaax** [comment]
> > I actually experienced this myself, I fixed it by moving the entire `init()` function to just global context rather than running it on script start.
> > I remembered there was something weird about exports and them having to be run on the first tick and made me give it a try. works like a charm now.
> 
> can you show how and where you did it?

Sorry, it took so long, have a look at my pr: https://github.com/snakewiz/fivem-appearance/pull/12

**Comment by CyanFlare** [comment]
> > > I actually experienced this myself, I fixed it by moving the entire `init()` function to just global context rather than running it on script start.
> > > I remembered there was something weird about exports and them having to be run on the first tick and made me give it a try. works like a charm now.
> > 
> > 
> > can you show how and where you did it?
> 
> Sorry, it took so long, have a look at my pr: #12

This worked for me thanks!

**Comment by mufty** [comment]
yeah it works now thanks

**Comment by pedr0fontoura** [comment]
Fixed on the latest release. Thanks @Cyntaax
