### ISSUE TITLE
When cancel it removes all weapons!

### ISSUE THREAD

**Issue by Kraleemil** [pedr0fontoura/fivem-appearance#84]
Hi i have the problem where if you cancel when you are in the editor. ![image](https://user-images.githubusercontent.com/64910903/208254724-7a6b1afa-25ac-49b7-9cf2-c6654a80b192.png)
Its like your ped gets respawned and you lose all your weapons

**Comment by Kraleemil** [comment]
@pedr0fontoura

**Comment by Kraleemil** [comment]
@pedr0fontoura

**Comment by Kraleemil** [comment]
> Store player weapons before opening the customization and apply them after you exit it. 
> 
> If players change their model while on customization the weapons are removed, and that's the general use case. I can't make a workaround on the script thinking about each specific use case.

How can I do that in typescript, i haven't been coding in it before

**Comment by pedr0fontoura** [comment]
You don't need to make changes to the **fivem-appearance** source code.

This workaround should be done on your side, where you call the startPlayerCustomization export.

Something like:

```lua
local weapons = MyFrameworkFunctionToGetPlayerWeapons(PlayerPedId())

exports['fivem-appearance']:startPlayerCustomization(...)

MyFrameworkFunctionToApplyPlayerWeapons(PlayerPedId(), weapons)
```

**Comment by Kraleemil** [comment]
> You don't need to make changes to the **fivem-appearance** source code.
> 
> This workaround should be done on your side, where you call the startPlayerCustomization export.
> 
> Something like:
> 
> ```lua
> local weapons = MyFrameworkFunctionToGetPlayerWeapons(PlayerPedId())
> 
> exports['fivem-appearance']:startPlayerCustomization(...)
> 
> MyFrameworkFunctionToApplyPlayerWeapons(PlayerPedId(), weapons)
> ```


Arhh you just want to do it that way, didn't even think about that
